apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  # namespace: argocd
  # Non-Cascade Delete
  finalizers: null
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 5.16.0
    # targetRevision: 5.53.14
    helm:
      releaseName: argocd
      # valueFiles:
      #   - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated:
      # prune: true
      # selfHeal: true
