apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hdfz-app
  # namespace: argocd
  # Non-Cascade Delete
  finalizers: null
spec:
  project: default
  source:
    repoURL: https://github.com/jameelkaisar/argocd-upgrade.git
    targetRevision: HEAD
    path: ./manifests/hdfz-app
  destination:
    server: https://kubernetes.default.svc
    namespace: hdfz-app
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
    - CreateNamespace=true
    # automated:
      # prune: true
      # selfHeal: true
