apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark-hpa
  # namespace: argocd
  # Non-Cascade Delete
  finalizers: null
spec:
  project: default
  source:
    repoURL: https://github.com/jameelkaisar/argocd-upgrade.git
    targetRevision: HEAD
    path: ./manifests/kubeshark-hpa
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated:
      # prune: true
      # selfHeal: true
