apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  # namespace: argocd
  # Non-Cascade Delete
  finalizers: null
spec:
  project: default
  source:
    repoURL: https://github.com/jameelkaisar/argocd-upgrade.git
    targetRevision: HEAD
    path: ./manifests/nginx-helm
    # targetRevision: main
    helm:
      releaseName: nginx-helm
      parameters:
      - name: replicaCount
        value: '2'
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-helm
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated:
      # prune: true
      # selfHeal: true
