apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hdfz-app
  # namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jameelkaisar/argocd-test.git
    targetRevision: HEAD
    path: ./multi-app/manifests/hdfz-app
  destination:
    server: https://kubernetes.default.svc
    namespace: hdfz-app
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
