apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  # namespace: argocd
  # Non-Cascade Delete
  finalizers: null
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.21.1
    helm:
      releaseName: istio-base
      parameters:
      - name: defaultRevision
        value: default
      # valueFiles:
      #   - ./_values/istiod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/failurePolicy
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated:
      # prune: true
      # selfHeal: true
