apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  # namespace: argocd
  # Non-Cascade Delete
  finalizers: null
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.21.1
    helm:
      releaseName: istio-ingressgateway
      parameters:
      - name: service.type
        value: NodePort
      # valueFiles:
      #   - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      # prune: true
      selfHeal: true
