apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-microservice
  # namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jameelkaisar/argocd-test.git
    targetRevision: HEAD
    path: ./multi-app/manifests/my-microservice
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-old
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
