apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  # namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jameelkaisar/argocd-test.git
    targetRevision: HEAD
    path: ./multi-app/manifests/nginx-helm
    # targetRevision: main
    helm:
      releaseName: nginx-helm
      parameters:
      - name: replicaCount
        value: '2'
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-helm
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
