apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  type: NodePort
  selector:
    app: nginx
    release: {{ .Release.Name }}
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
