apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  labels:
    app: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - name: api-app
        image: ghcr.io/jameelkaisar/argocd-test/api-app:v1
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 5000
          protocol: TCP
